# Generated by Django 4.2.4 on 2023-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationitem',
            name='verb',
            field=models.CharField(default='', max_length=255, verbose_name='Verb'),
            preserve_default=False,
        ),
    ]
