# Generated by Django 4.2.4 on 2023-11-07 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself. (Markdown and BBCode Supported)', max_length=500, verbose_name='About Me')),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default/avatar.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[600, 600], upload_to='avatars', verbose_name='Profile Picture')),
                ('header', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 400], upload_to='headers', verbose_name='Header Picture')),
                ('use_gravtar', models.BooleanField(default=False, help_text='Use Gravatar instead of a profile picture', verbose_name='Use Gravatar')),
                ('location', models.CharField(blank=True, help_text='City, State, Country', max_length=30, verbose_name='Location')),
                ('website', models.URLField(blank=True, help_text='Your Website URL', max_length=100, verbose_name='Website')),
                ('rank', models.IntegerField(default=0, help_text='The rank of the user in the leaderboard', verbose_name='Rank')),
                ('muted_users', models.ManyToManyField(related_name='muted_users', to=settings.AUTH_USER_MODEL, verbose_name='Muted Users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('email_notifications_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', help_text='How often do you want to receive email notifications?', max_length=20, verbose_name='Email Notifications Frequency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
