# Generated by Django 4.2.4 on 2023-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode for the website', verbose_name='Dark Mode'),
        ),
    ]
