# Generated by Django 4.2.4 on 2025-06-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dark_mode',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
