# Generated by Django 4.2.4 on 2023-08-28 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usersession_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
