# Generated by Django 4.2.4 on 2023-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, State, Country', max_length=30, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Your Website URL', max_length=100, verbose_name='Website'),
        ),
    ]
