# Generated by Django 4.2.4 on 2023-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_use_gravtar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='use_gravtar',
            field=models.BooleanField(default=False, help_text='Use Gravatar instead of a profile picture', verbose_name='Use Gravatar'),
        ),
    ]
