# Generated by Django 4.2.4 on 2023-11-02 12:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_use_gravtar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='header',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 400], upload_to='headers', verbose_name='Header Picture'),
        ),
    ]
