# Generated by Django 4.2.4 on 2023-11-07 09:34

import apps.account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('created_by', models.ForeignKey(on_delete=models.SET(apps.account.models.get_sentinel_user), related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('voted_by', models.ManyToManyField(blank=True, related_name='voted_questions', to=settings.AUTH_USER_MODEL, verbose_name='Votes')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='No. of Votes')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
