# Generated by Django 4.2.4 on 2023-10-13 14:03

import apps.account.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.account.models.get_sentinel_user), related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
