# Generated by Django 4.2.4 on 2023-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_question_voted_by_remove_choice_votes_choice_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='No. of Votes'),
        ),
    ]
