# Generated by Django 4.2.4 on 2024-09-04 06:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None),
        ),
    ]
