# Generated by Django 4.2.4 on 2025-06-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select category for this post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.category', verbose_name='Category'),
        ),
    ]
