# Generated by Django 4.2.4 on 2023-10-11 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_post_category_remove_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(help_text='Select category for this post.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.category', verbose_name='Category'),
        ),
    ]
