# Generated by Django 4.2.4 on 2023-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked threads cannot be replied to.', verbose_name='Locked'),
        ),
    ]
